server:
  port: 8082

spring:
  application:
    name: candidate-service
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;databaseName=Candidate_ats;encrypt=false;
    username: sa
    password: 1234

    hikari:
      pool-name: CandidateHikariPool
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 60000
      max-lifetime: 100000

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.SQLServerDialect
    open-in-view: false

